news_project/app/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView, ArticleDetailView, ArticleFilterView


urlpatterns = [
    path("", ItemFilterView.as_view(), name="index"),
    path("detail/<int:pk>/", ItemDetailView.as_view(), name="detail"),
    path("create/", ItemCreateView.as_view(), name="create"),
    path("update/<int:pk>/", ItemUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ItemDeleteView.as_view(), name="delete"),
    path("filter/<int:pk>/", ItemFilterView.as_view(), name="filter"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article"),
    path("query/<int:pk>/", ArticleFilterView.as_view(), name="query"),
]

news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
]

news_project/app/models.py
from django.db import models
from django.core import validators
# from djongo import models


class Item(models.Model):
    SEX_CHOICE = ((1, "Male"), (2, "Female"))
    name = models.CharField(
        verbose_name="Name",
        max_length=200,
    )
    age = models.IntegerField(
        verbose_name="Age",
        validators=[validators.MinValueValidator(1)],
        blank=True,
        null=True
    )
    sex = models.IntegerField(
        verbose_name="Sex",
        choices=SEX_CHOICE,
        default=1
    )
    memo = models.TextField(
        verbose_name="Memo",
        max_length=300,
    )
    created_at = models.DateTimeField(
        verbose_name="register date",
        auto_now_add=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Item"


class Article(models.Model):
    _id = models.TextField()
    site = models.CharField(
        verbose_name="NewsSite",
        max_length=200,
    )
    title = models.CharField(
        verbose_name="News Title",
        max_length=300,
    )
    article = models.TextField(
        verbose_name="News Article",
    )
    stored_at = models.DateTimeField(
        verbose_name="Stored date"
    )
    url = models.CharField(
        verbose_name="News URL",
        max_length=300,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Article"

news_project/app/forms.py
from django import forms
from .models import Item, Article


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = {"name", "age", "sex", "memo"}
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "記入例: "}),
            "age": forms.NumberInput(attrs={"min": 1}),
            "sex": forms.RadioSelect(),
            "memo": forms.Textarea(attrs={"rows": 4})
        }


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = {"site", "title", "article", "stored_at", "url"}
        widgets = {
            "site": forms.Textarea(attrs={"cols": 80, "rows": 5}),
            "title": forms.Textarea(attrs={"cols": 80, "rows": 5}),
            "article": forms.Textarea(attrs={"cols": 80, "rows": 20}),
            "stored_at": forms.Textarea(attrs={"cols": 80, "rows": 20}),
            "url": forms.Textarea(attrs={"cols": 80, "rows": 20}),
        }

news_project/app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .models import Item, Article
from .filters import ItemFilter, ArticleFilter
from .forms import ItemForm, ArticleForm


class ItemFilterView(LoginRequiredMixin, FilterView):
    model = Item
    filterset_class = ItemFilter
    queryset = Item.objects.all().order_by("-created_at")
    strict = False
    paginate_by = 10

    def get(self, request, **kwargs):
        if request.GET:
            request.session["query"] = request.GET
        else:
            request.GET = request.GET.copy()
            if "quety" in request.session.keys():
                for key in request.session["query"].keys():
                    request.GET[key] = request.session["query"][key]
        return super().get(request, **kwargs)


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy("index")


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy("index")


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy("index")


class ArticleFilterView(LoginRequiredMixin, FilterView):
    model = Article
    filterset_class = ArticleFilter
    queryset = Article.objects.all().order_by("-created_at")
    strict = False
    paginate_by = 10

    def get(self, request, **kwargs):
        if request.GET:
            request.session["query"] = request.GET
        else:
            request.GET = request.GET.copy()
            if "query!" in request.session.keys():
                for key in request.session["query"].keys():
                    request.GET[key] = request.session["query"][key]
        return super().get(request, **kwargs)


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article

news_project/app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Application Name</title>
    <!-- Bootstrap CSS -->
    <link href="https:maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'app/css/app.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Application Name</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="Navigation toggle">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="Navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">Admin Site</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout %'}">Logout</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="{% static 'app/js/plugin/responsive-paginate.js' %}"></script>
    <script src="{% static 'app/js/app.js' %}"></script>
</body>
</html>

news_project/app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% end if%}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">((page ))</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disable page-item pagination-next">
            <span class="page-link">&raquo;</span>
        </li>
    {% endif %}
</ul>

news_project/app/templates/app/item_card.html
<div class="row">
    <div class="col-3">
        <p>Name</p>
    </div>
    <div class="col-9">
        <p>{{ item.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>Age</p>
    </div>
    <div class="col-9">
        <p>{{ item.age }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>Sex</p>
    </div>
    <div class="col-9">
        <p>{{ item.get_sex_display }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>Memo</p>
    </div>
    <div class="col-9">
        <p>{{ item.memo|linebreaksbr }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>Register Date</p>
    </div>
    <div class="col-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

news_project/app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!-- -->
{% block content %}
<div class="container">
    <h2 class="text-center">Delete Data</h2>
    <p>Do you delete this Data?</p>

    <form action="" method="post">
        {% csrf_token %>
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">Back</a>
                    <input type="submit" class="btn btn-outline-secondary" value="Delete"/>
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">Back</a>
                    <input type="submit" class="btn btn-outline-secondary" value="Delete">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

news_project/app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h2 class="text-center">Detail View</h2>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">Back</a>
        </div>
    </div>
    <!-- -->
    {% include "./item_card.html" %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">Back</a>
        </div>
    </div>
</div>
{% endblock %}

news_project/app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div id="myModal" class="myModal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Filter</h5>
                    <button type="Button" class="close" data-dismiss="modal" aria-label="Close"></button>
                        <span aria-hidden="true">&times;</times></span>
                </div>
                <form id="filter" method="get">
                    <div class="modal-body">
                        {{filter.form|crispy}}
                    </div>
                </form>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" data-dismiss="modal">Back</a>
                    <button type="submit" class="btn btn-outline-secondary" form="filter">Search</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">Cancellation Search</a>
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">New</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">Search</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for item in item_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-3">
                            <p>Name</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>Register Date</p>
                        </div>
                        <div class="col-9">
                            <p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'detail' item.pk %}">detail0</a>
                                <a class="btn btn-outline-secondary " href="{% url 'update' item.pk %}">edit</a>
                                <a class="btn btn-outline-secondary " href="{% url 'delete' item.pk %}">delete</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    don't exist data
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row" >
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">New</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">Search</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

news_project/app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">Input data</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">Back</a>
                <a class="btn btn-outline-secondary save" href="#">Save</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">Back</a>
                <a class="btn btn-outline-secondary save" href="#">Save</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}